In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Create a sample dataset
data = [[1, 2], [3, 4], [5, 6]]

# Create an instance of PolynomialFeatures
poly = PolynomialFeatures(degree=2)

# Fit and transform the data
data_poly = poly.fit_transform(data)

# Print the transformed data
print(data_poly)

[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]
